# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f432f1fcd93efa4506dc05007756163a158a81754d43f411612559eb8d449b5f0e8d8423179455bb379ece9d142aeee5af34a5af979c1aff010505f9534e5f0

test:
  secret_key_base: 2d536af80405be06299606a18274cddbdfeb163e9bd7dc2fbc4a4af14966afb3133ae3fef4680ef0a851958e79921b9f83314dee89179daa96adbf82df9a2c58

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
